# Generated by Django 4.2.11 on 2026-03-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "cert_type",
                    models.CharField(
                        choices=[
                            ("Completion", "Completion"),
                            ("Excellence", "Excellence"),
                            ("Participation", "Participation"),
                            ("Achievement", "Achievement"),
                        ],
                        default="Completion",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "cert_number",
                    models.CharField(default="", max_length=50, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "certificates",
                "ordering": ["-issue_date"],
            },
        ),
    ]
