# Generated by Django 4.2.11 on 2026-03-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("certificates", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="students.student",
            ),
        ),
    ]
