# Generated by Django 4.2.11 on 2026-03-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("grade", models.CharField(blank=True, max_length=50)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Contacted", "Contacted"),
                            ("Interested", "Interested"),
                            ("Trial", "Trial"),
                            ("Enrolled", "Enrolled"),
                            ("Lost", "Lost"),
                        ],
                        default="New",
                        max_length=15,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Referral", "Referral"),
                            ("Social Media", "Social Media"),
                            ("Website", "Website"),
                            ("Walk-in", "Walk-in"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("follow_up", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "enquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
