# Generated by Django 4.2.11 on 2026-03-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="follow_up",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="source",
            field=models.CharField(
                choices=[
                    ("Referral", "Referral"),
                    ("Social Media", "Social Media"),
                    ("Website", "Website"),
                    ("Walk-in", "Walk-in"),
                    ("Other", "Other"),
                ],
                db_index=True,
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="stage",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Contacted", "Contacted"),
                    ("Interested", "Interested"),
                    ("Trial", "Trial"),
                    ("Converted", "Converted"),
                    ("Rejected", "Rejected"),
                ],
                db_index=True,
                default="New",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="subject",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
