# Generated by Django 4.2.11 on 2026-03-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0002_alter_enquiry_created_at_alter_enquiry_follow_up_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry",
            name="grade",
        ),
    ]
