"use client";

import { useState, useEffect } from "react";
import { Plus, Award, Trash2, Download, CheckCircle, Clock } from "lucide-react";
import { getAll, createOne, deleteOne } from "@/lib/storage";
import { showToast } from "@/components/ui/Toast";
import Modal from "@/components/ui/Modal";
import clsx from "clsx";

interface Certificate {
  id: number;
  student: number;
  student_name?: string;
  course: number | null;
  course_title?: string;
  title: string;
  description: string;
  cert_number: string;
  cert_type: string;
  issue_date: string;
  status?: "Issued" | "Pending";
}

interface Student {
  id: number;
  name: string;
  course?: string;
}

interface Course {
  id: number;
  title: string;
}

const BLANK = {
  student: "",
  course: "",
  title: "",
  cert_type: "Completion",
  issue_date: new Date().toISOString().split("T")[0],
  description: "",
};

export default function CertificatesPage() {
  const [certs, setCerts]         = useState<Certificate[]>([]);
  const [students, setStudents]   = useState<Student[]>([]);
  const [courses, setCourses]     = useState<Course[]>([]);
  const [loading, setLoading]     = useState(true);
  const [saving, setSaving]       = useState(false);
  const [modalOpen, setModal]     = useState(false);
  const [form, setForm]           = useState(BLANK);
  const [deleteId, setDeleteId]   = useState<number | null>(null);

  useEffect(() => {
    (async () => {
      try {
        const [certsData, studentsData, coursesData] = await Promise.all([
          getAll("certificates"),
          getAll("students"),
          getAll("courses"),
        ]);
        setCerts(certsData);
        setStudents(studentsData);
        setCourses(coursesData);
      } catch {
        showToast("Failed to load certificates. Please try again.");
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const handleCreate = async () => {
    if (!form.student || !form.title.trim()) return;
    setSaving(true);
    try {
      const payload = {
        student: Number(form.student),
        course: form.course ? Number(form.course) : null,
        title: form.title,
        cert_type: form.cert_type,
        issue_date: form.issue_date,
        description: form.description,
        // Do NOT send cert_number — it's auto-generated by the backend
      };
      const created = await createOne("certificates", payload);
      setCerts(prev => [created, ...prev]);
      setModal(false);
      setForm(BLANK);
    } catch {
      showToast("Failed to issue certificate. Please try again.");
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (id: number) => {
    try {
      await deleteOne("certificates", id);
      setCerts(prev => prev.filter(c => c.id !== id));
      setDeleteId(null);
    } catch {
      showToast("Failed to delete certificate. Please try again.");
    }
  };

  const stats = {
    total: certs.length,
    issued: certs.filter(c => c.status === "Issued" || c.issue_date).length,
    pending: certs.filter(c => c.status === "Pending").length,
  };

  return (
    <div className="space-y-6 animate-fade-in max-w-6xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-text-primary flex items-center gap-2">
            <Award size={20} className="text-primary-500" /> Certificates
          </h1>
          <p className="text-sm text-text-muted mt-0.5">
            {stats.issued} issued • {stats.pending} pending
          </p>
        </div>
        <button onClick={() => { setForm(BLANK); setModal(true); }} className="btn-primary">
          <Plus size={16} /> Issue Certificate
        </button>
      </div>

      {loading ? (
        <div className="page-card text-center py-16">
          <Award size={40} className="mx-auto text-surface-border mb-3" />
          <p className="text-sm font-semibold text-text-muted animate-pulse">Loading certificates…</p>
        </div>
      ) : certs.length === 0 ? (
        <div className="page-card text-center py-16">
          <Award size={40} className="mx-auto text-surface-border mb-3" />
          <p className="text-sm font-semibold text-text-muted">No certificates exist yet.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {certs.map((c) => {
            const isIssued = c.status !== "Pending";
            return (
              <div
                key={c.id}
                className={clsx(
                  "relative page-card !p-0 overflow-hidden group border",
                  isIssued ? "border-surface-border" : "border-warning-500/30 bg-warning-500/10"
                )}
              >
                {/* Decorative side bar */}
                <div
                  className={clsx(
                    "absolute left-0 top-0 bottom-0 w-1",
                    isIssued ? "bg-primary-500" : "bg-warning-500"
                  )}
                />

                <div className="p-5 pl-6">
                  <div className="flex justify-between items-start mb-3">
                    <div>
                      <h3 className="text-base font-bold text-text-primary">{c.student_name ?? `Student #${c.student}`}</h3>
                      <p className="text-xs text-text-muted font-medium mt-0.5">{c.course_title ?? c.title}</p>
                    </div>
                    <span
                      className={clsx(
                        "badge border flex items-center gap-1",
                        isIssued
                          ? "bg-success-500/20 text-success-400 border-success-500/30"
                          : "bg-warning-500/20 text-warning-500 border-warning-500/30"
                      )}
                    >
                      {isIssued ? <CheckCircle size={10} /> : <Clock size={10} />}
                      {isIssued ? "Issued" : "Pending"}
                    </span>
                  </div>

                  <div className="flex items-center gap-6 mt-4 pb-4 border-b border-surface-border">
                    <div>
                      <p className="text-[10px] uppercase font-bold text-text-secondary tracking-wider mb-1">Type</p>
                      <p className="text-base font-black text-text-primary">{c.cert_type}</p>
                    </div>
                    <div>
                      <p className="text-[10px] uppercase font-bold text-text-secondary tracking-wider mb-1">Cert No.</p>
                      <p className="text-sm font-semibold text-text-primary mt-1.5">{c.cert_number || "—"}</p>
                    </div>
                    <div>
                      <p className="text-[10px] uppercase font-bold text-text-secondary tracking-wider mb-1">Issue Date</p>
                      <p className="text-sm font-semibold text-text-primary mt-1.5">{c.issue_date}</p>
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="flex items-center justify-between pt-3">
                    <button className="flex items-center gap-1.5 text-xs font-semibold text-primary-600 hover:text-primary-700 transition-colors">
                      <Download size={14} /> Download PDF
                    </button>

                    {deleteId === c.id ? (
                      <div className="flex items-center gap-1 bg-[var(--surface-card)] p-1 rounded-lg border border-surface-border">
                        <button
                          onClick={() => handleDelete(c.id)}
                          className="text-[10px] font-bold px-2 py-1 bg-danger-500 text-white rounded"
                        >
                          Confirm
                        </button>
                        <button
                          onClick={() => setDeleteId(null)}
                          className="text-[10px] font-bold px-2 py-1 bg-surface-muted text-text-primary rounded"
                        >
                          Cancel
                        </button>
                      </div>
                    ) : (
                      <button
                        onClick={() => setDeleteId(c.id)}
                        className="p-1.5 rounded-lg text-text-muted hover:bg-danger-50 hover:text-danger-500 transition-colors"
                      >
                        <Award size={14} />
                      </button>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Issue Modal */}
      <Modal isOpen={modalOpen} title="Issue Certificate" onClose={() => setModal(false)}>
        <div className="space-y-4">
          <div>
            <label className="block text-xs font-semibold text-text-secondary mb-1.5 uppercase tracking-wide">Select Student</label>
            <select value={form.student} onChange={e => setForm(p => ({ ...p, student: e.target.value }))} className="input-field">
              <option value="">-- Choose a student --</option>
              {students.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </div>

          <div>
            <label className="block text-xs font-semibold text-text-secondary mb-1.5 uppercase tracking-wide">Select Course</label>
            <select value={form.course} onChange={e => setForm(p => ({ ...p, course: e.target.value }))} className="input-field">
              <option value="">-- Choose a course (optional) --</option>
              {courses.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}
            </select>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-text-secondary mb-1.5 uppercase tracking-wide">Certificate Title</label>
              <input value={form.title} onChange={e => setForm(p => ({ ...p, title: e.target.value }))} placeholder="e.g. Course Completion" className="input-field" />
            </div>
            <div>
              <label className="block text-xs font-semibold text-text-secondary mb-1.5 uppercase tracking-wide">Certificate Type</label>
              <select value={form.cert_type} onChange={e => setForm(p => ({ ...p, cert_type: e.target.value }))} className="input-field">
                {["Completion", "Excellence", "Participation", "Achievement"].map(v => <option key={v}>{v}</option>)}
              </select>
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-text-secondary mb-1.5 uppercase tracking-wide">Issue Date</label>
            <input type="date" value={form.issue_date} onChange={e => setForm(p => ({ ...p, issue_date: e.target.value }))} className="input-field" />
          </div>

          <div>
            <label className="block text-xs font-semibold text-text-secondary mb-1.5 uppercase tracking-wide">Description</label>
            <textarea rows={2} value={form.description} onChange={e => setForm(p => ({ ...p, description: e.target.value }))} placeholder="Optional description…" className="input-field resize-none" />
          </div>

          <div className="flex justify-end gap-3 pt-2">
            <button onClick={() => setModal(false)} className="px-4 py-2 text-sm border border-surface-border rounded-xl hover:bg-surface-muted">Cancel</button>
            <button onClick={handleCreate} disabled={!form.student || !form.title.trim() || saving} className="btn-primary disabled:opacity-50">
              {saving ? "Issuing…" : "Issue Certificate"}
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
