# Generated by Django 4.2.11 on 2026-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_avatars/"
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=50)),
                ("subject", models.CharField(blank=True, max_length=100)),
                (
                    "score",
                    models.FloatField(
                        default=0.0, help_text="Current average score 0-100"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("At Risk", "At Risk"),
                            ("Graduated", "Graduated"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "students",
                "ordering": ["name"],
            },
        ),
    ]
