# Generated by Django 4.2.11 on 2026-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableslot",
            name="mode",
            field=models.CharField(
                choices=[("Online", "Online"), ("Offline", "Offline")],
                default="Online",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="timetableslot",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("Lecture", "Lecture"),
                    ("Tutorial", "Tutorial"),
                    ("Lab", "Lab"),
                    ("Test", "Test"),
                    ("Revision", "Revision"),
                ],
                default="Lecture",
                max_length=15,
            ),
        ),
    ]
